config/routes.rb
WordpressVersionChecker::Application.routes.draw do

  resources :sites

  root :to => "sites#index"

  devise_for :users
  resources :users, :only => :show

end

app/models/site.rb
class Site
  include Mongoid::Document
  include Mongoid::Timestamps
  field :url, :type => String
  field :name, :type => String
  
  validates_presence_of :url
  validates_uniqueness_of :url, :case_sensitive => false

  before_create :get_name
  
  def self.create_from_url(url)
    
    site = Site.find_or_create_by(:url => url)

    site
    
  end

  protected
  def get_name

    begin 
    
      require 'hpricot'
      require 'open-uri'
    
      doc = Hpricot(open(self.url.httpize))
      self.name = doc.at('title').to_plain_text

    rescue
      
      self.name = self.url.dehttpize
      
    end
    
  end
  
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all

  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!

  def index

    @sites = Site.all

  end
  
  def new
    
    @site = Site.new
    
  end
  
  def create
    
    site = Site.create_from_url(params[:site][:url])
    
    redirect_to edit_site_path(site)
    
  end
  
  def show
    
    @site = Site.find(params[:id])
    
  end

  def edit
    
    @site = Site.find(params[:id])
    
  end

  def update

    site = Site.find(params[:id])
    
    site.update_attributes(:name => params[:site][:name])
  
    redirect_to site_path(site)
  
  end
    
  
  def destroy
    
    Site.find(params[:id]).destroy
    
    redirect_to sites_path
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Testapp
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %h1
      = link_to 'WordPress Version Checker', '/'
    %ul.hmenu
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'
    %p{:style => "color: green"}= notice
    %p{:style => "color: red"}= alert
    = yield

app/views/sites/edit.html.haml
= render 'sites/menu/main'
= form_for @site do |f|

  = f.label :name
  = f.text_field :name

  = f.label :url
  = f.text_field :url

  = f.submit

app/views/sites/index.html.haml
= render 'sites/menu/main'
%ul
  - @sites.each do |site|
    %li 
      %span= link_to site.name, site_path(site)
      %ul
        %li= link_to 'Edit', edit_site_path(site)
        %li= link_to 'Delete', site_path(site), :method => :delete, :confirm => "Are you sure?"

app/views/sites/menu/_main.html.haml
%h1 Sites
%ul
  %li
    = link_to 'List', sites_path
    = link_to 'New', new_site_path

app/views/sites/new.html.haml
= render 'sites/menu/main'
= form_for @site do |f|
  = f.label :url
  = f.text_field :url

  = f.submit

app/views/sites/show.html.haml
= render 'sites/menu/main'
%h2= @site.name
%span.url= @site.url


%p= link_to 'Edit', edit_site_path(@site)
%p= link_to 'Delete', site_path(@site), :method => :delete, :confirm => "Are you sure?"

app/views/users/show.html.haml
%p
  User: #{@user.name}